version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=TheUntraceable
      - MONGO_INITDB_ROOT_PASSWORD=z0-:#BqSm00Y*B!l
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - 27017:27017
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - 2340:2340
    depends_on:
      - mongodb
