name: RUFF

on:
  push:
    branches: [ master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install ruff
      - name: Run RUFF
        run: ruff